"""
=============================================================================
  DEMO: Final Report Agent & Report Tool
  Author: Hirun Athukorala (Report Agent Module)
  Assignment: CTSE - Multi-Agent System (MAS) - Sri Lanka Travel Planner
=============================================================================

Run this file to demonstrate YOUR part of the MAS to the panel:
    py -3.11 demo_report_agent.py
"""

import sys
import os
import time
import logging

# Silence tool-level logs so only clean demo output is visible to the panel
logging.disable(logging.CRITICAL)

sys.path.insert(0, os.path.abspath("src"))

from crewai import Agent, Task, Crew, Process, LLM
from agents.report_agent import create_report_agent
from tasks.report_task import create_report_task
from tools.report_tool import save_report_to_file

# ─── helpers ─────────────────────────────────────────────────────────────────

def divider(title: str = ""):
    print("\n" + "=" * 65)
    if title:
        print(f"  {title}")
        print("=" * 65)

def pause(msg: str = ""):
    if msg:
        print(f"\n  >>> {msg}")
    time.sleep(0.4)

# ─── DEMO ────────────────────────────────────────────────────────────────────

def main():
    print()
    print("=" * 65)
    print("   FINAL REPORT AGENT — LIVE DEMO")
    print("   Author : Hirun Athukorala")
    print("   Module : Report Agent & Report Tool")
    print("   MAS    : Sri Lanka Travel Planner (CrewAI + Ollama)")
    print("=" * 65)

    # ── 1. Show the tool is saving files locally ──────────────────────────────
    divider("STEP 1 — Custom Tool: save_report_to_file()")
    print("  This tool writes the generated markdown to the filesystem.")
    
    test_filename = "TEST_report_output.md"
    test_content = "# Test Travel Plan\nThis is a test generated by the report tool."
    
    print(f"  Attempting to save '{test_filename}'...")
    result = save_report_to_file(test_content, test_filename)
    print(f"  Result: {result}")
    
    if os.path.exists(test_filename):
        print(f"  [SUCCESS] File {test_filename} was created.")
        # Cleanup
        os.remove(test_filename)
        print(f"  [CLEANUP] Deleted test file.")
    
    pause("Tool verified: successfully creates files on the local filesystem.")

    # ── 2. Run a Mock Pipeline with the Agent ─────────────────────────────────
    divider("STEP 2 — Running the Report Agent with Mock Context")
    print("  We will simulate the outputs of the Research and Hotel agents")
    print("  and feed them directly to the Report Agent to generate the final file.")

    llm = LLM(
        model="ollama/qwen2.5",
        base_url="http://localhost:11434",
    )

    # Mock context tasks to pass data to the report agent
    mock_research_agent = Agent(role="Mock", goal="Mock", backstory="Mock", llm=llm)
    
    mock_context_task = Task(
        description="Just return this exact text as output.",
        expected_output="Mock context",
        agent=mock_research_agent
    )
    
    # We forcefully set the output to simulate the prior agents
    mock_context = """
# Research Output for Kandy (3 Days)
- Temple of the Tooth: $15 USD. 4.8/5.0. Must visit.
- Kandy Lake: Free. Great for a walk.
- Royal Botanical Gardens: $15 USD. Huge variety of plants.

# Hotel Output
1. Hotel Suisse Kandy - $85/night - 4.2/5.0
2. Earl's Regency Hotel - $120/night - 4.5/5.0
"""
    
    print("\n  [Mock Context Provided to Agent]:")
    print("  " + "\n  ".join(mock_context.strip().split("\n")))
    
    report_task = create_report_task("Kandy", 3, llm)
    
    # Normally context is handled by CrewAI sequential process, 
    # but here we set it explicitly for the demo
    report_task.context = [mock_context_task]
    
    # A small hack to inject context directly for the demo without running other agents
    report_task.description = f"Here is the context from previous agents:\n{mock_context}\n\n" + report_task.description
    
    crew = Crew(
        tasks=[report_task],
        process=Process.sequential,
        verbose=True
    )
    
    print("\n  >>> Kicking off CrewAI for the Report Agent (Please wait)...")
    
    try:
        crew.kickoff()
        print("\n  >>> Agent completed its task.")
        
        expected_file = "Kandy_travel_plan.md"
        if os.path.exists(expected_file):
            print(f"\n  [SUCCESS] {expected_file} was created by the Agent!")
            print("  Here is the first 250 characters of the file:\n")
            with open(expected_file, "r") as f:
                content = f.read()
                print("-" * 40)
                print(content[:250] + "...\n(truncated)")
                print("-" * 40)
            pause("Agent successfully used the tool to save the formatted report.")
        else:
            print(f"\n  [WARNING] {expected_file} was not found. Agent might have failed or Hallucinated filename.")
            
    except Exception as e:
        print(f"\n  [WARNING] Could not execute the agent. Is Ollama running?")
        print(f"  Error details: {e}")

    # ── Final summary ─────────────────────────────────────────────────────────
    divider("DEMO COMPLETE")
    print("  MY CONTRIBUTION SUMMARY:")
    print()
    print("  1. AGENT  : src/agents/report_agent.py")
    print("              -> Executive Travel Report Editor")
    print("              -> Synthesizes outputs into final Markdown.")
    print()
    print("  2. TOOL   : src/tools/report_tool.py")
    print("              -> save_report_to_file()")
    print("              -> Persists the final itinerary to the disk safely.")
    print()
    print("  3. TASK   : src/tasks/report_task.py")
    print("              -> Guides the agent on structure (Title, Days, Hotels).")
    print()
    print("  4. CREW   : src/app/crew.py")
    print("              -> Integrated as the final step in the pipeline.")
    print()
    print("  Ready to integrate with the full CrewAI crew (py main.py).")
    print("=" * 65)

if __name__ == "__main__":
    main()
